### ISSUE TITLE
Unite 2

### ISSUE THREAD

**Issue by bhargavchauhan86** [manjotsidhu/wakemod#6]
Lineage os wakemod unknown basbend

**Comment by imranpopz** [comment]
https://drive.google.com/file/d/0BwLeJ-n7ENnxeHR4aTBsZ0o1MVE/view

Try this and report...

**Comment by bhargavchauhan86** [comment]
Bro this is not working

**Comment by manjotsidhu** [comment]
http://manjotsidhu.com/fix/
